services:
  docker-hosts:
    container_name: docker-hosts
    build: .
    restart: always
    init: true
    volumes:
      - ./templates:/data/templates
      - /var/run/docker.sock:/var/run/docker.sock
      #- /opt/dns/zones/containers.local.db:/data/zone:rw,z
      - /etc/hosts:/data/hosts:rw,z
    environment:
      - TEMPLATE=hosts
      - RELOAD_CONTAINERS=caddy:exec(caddy reload --config /etc/caddy/Caddyfile)
    network_mode: none
