services:
  docker-hosts:
    container_name: docker-hosts
    build: .
    restart: always
    init: true
    volumes:
      - ./templates:/data/templates
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/dns/zones/containers.local.db:/data/zone
    environment:
      - TEMPLATE=dns-zone
      - RELOAD_CONTAINERS=dns:kill(SIGUSR1),caddy:exec(caddy reload --config /etc/caddy/Caddyfile)
    network_mode: none
