name: Publish

on:
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
    build:
        runs-on: ubuntu-latest
        if: github.repository_owner == 'donovandmc'
        needs: [lint]
        steps:
            - uses: actions/checkout@v6
            - uses: docker/setup-buildx-action@v4
            - run: |
                  echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ vars.REGISTRY }} --username ${{ vars.REGISTRY_USERNAME }} --password-stdin
            - id: metadata
              uses: docker/metadata-action@v5
              with:
                  images: ${{vars.REGISTRY}}/${{vars.IMAGE_NAME}}
                  tags: |
                      type=sha,format=long,prefix=
                      type=semver,pattern={{version}}
                  flavor: |
                      latest=true
            - uses: docker/build-push-action@v7
              with:
                  push: true
                  tags: ${{ steps.metadata.outputs.tags }}
                  labels: ${{ steps.metadata.outputs.labels }}
                  cache-from: type=gha
